### ISSUE TITLE
OnNext() method crash the app.

### ISSUE THREAD

**Issue by rahulraghuwanshii** [shts/StoriesProgressView#41]
If progress finish and to start new story app careshes says 
  java.lang.IndexOutOfBoundsException: Index: 3, Size: 3
        at java.util.ArrayList.get(ArrayList.java:437)
        at com.padosi.activity.StoryViewActivity.loadImage(StoryViewActivity.java:141)
        at com.padosi.activity.StoryViewActivity.access$200(StoryViewActivity.java:29)
        at com.padosi.activity.StoryViewActivity$1.onNext(StoryViewActivity.java:44)
        at jp.shts.android.storiesprogressview.StoriesProgressView$1.onFinishProgress(StoriesProgressView.java:190)
        at jp.shts.android.storiesprogressview.PausableProgressBar$1.onAnimationEnd(PausableProgressBar.java:117)
        at android.view.animation.Animation.dispatchAnimationEnd(Animation.java:1011)
        at android.view.animation.Animation$3.run(Animation.java:390)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7519)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:995)

**Comment by mohamedAppetito** [comment]
do you have any fix for this issue ?

**Comment by mohamedAppetito** [comment]
can you tell me who crash happen , it happen with some user , but
idont know who happend
